# For workspace name
# The checkpoint file location to be saved: {workspace}/checkpoints/
# The log file location to be saved: {workspace}/tensorboard_logs/
workspace: ./finetune_funsd_el_spade__bros-base-uncased
#workspace: ./finetune_funsd_el_spade__layoutlm-base-uncased

dataset: funsd
task: el

model:
  backbone: naver-clova-ocr/bros-base-uncased
  #backbone: microsoft/layoutlm-base-uncased
  head: spade_rel
  head_hidden_size: 128
  head_p_dropout: 0.1

train:
  batch_size: 16
  num_samples_per_epoch: 149
  max_seq_length: 512
  max_epochs: 100
  use_fp16: True
  accelerator: gpu
  strategy:
    type: ddp

  clip_gradient_algorithm: norm
  clip_gradient_value: 1.0
  num_workers: 0

  optimizer:
    method: adamw
    params:
      lr: 5e-5
    lr_schedule:
      method: linear
      params:
        warmup_steps: 0

  val_interval: 1  # in epochs

val:
  batch_size: 8
  num_workers: 0
  limit_val_batches: 1.0

